#!/bin/sh

start() {
#    echo -n "Firmware rev: "
#    cat /etc/firmware_rev
#    modprobe r8152
#    modprobe sr9800
#    modprobe cdc_acm
#    modprobe spidev
#    modprobe snd-usb-audio
#    modprobe snd-intel8x0
#    modprobe uio
#    sleep 3
#    [ -d /sys/class/net/eth1 ] && dhclient -w -v eth1
    mount /dev/mmcblk0p1 /mnt
    tcpsvd 0:21 ftpd ftpd -w /&
    echo "done"

    echo -n "Starting custom drivers..."

    echo "done"
}

stop() {
    umount /mnt
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
