#!/bin/sh

start() {
#    echo -n "Firmware rev: "
#    mount /dev/mmcblk0p4 /mnt
    tcpsvd 0:21 ftpd ftpd -w /&
    echo "done"

    echo -n "Starting custom drivers..."

    echo "done"
}

stop() {
    umount /mnt
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
